version: '3'

services:
  server:
    container_name: nginx-static-webserver
    image: nginx
    restart: always
    ports:
      - 9085:80
    volumes:
      - ./data:/srv
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
